spring:
  application:
    name: common-market
  datasource:
    url: jdbc:mysql://localhost:3306/common_market # Connects to the MySQL Service in Kubernetes
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC Driver
    username: root # Matches the username in your Kubernetes Secret
    password: wkit3031! # Matches the password in your Kubernetes Secret
  jpa:
    hibernate:
      ddl-auto: update # Options: none, update, create, create-drop. Use 'update' for development.
    show-sql: true # Optional: Shows SQL queries in logs
    properties:
      hibernate:
        format_sql: true # Optional: Formats SQL queries in logs
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# JWT Configuration
jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidation2024
  expiration: 86400 # 24 hours in seconds