logging:
  level:
    org.hibernate.SQL: OFF # Log all SQL statements
    org.hibernate.type.descriptor.sql: OFF # Log SQL parameters (bind values)
spring:
  jpa:
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 1000
